/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, BlogEvent as PrismaBlogEvent } from "@prisma/client";

export class BlogEventServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.BlogEventCountArgs, "select">
  ): Promise<number> {
    return this.prisma.blogEvent.count(args);
  }

  async blogEvents(
    args: Prisma.BlogEventFindManyArgs
  ): Promise<PrismaBlogEvent[]> {
    return this.prisma.blogEvent.findMany(args);
  }
  async blogEvent(
    args: Prisma.BlogEventFindUniqueArgs
  ): Promise<PrismaBlogEvent | null> {
    return this.prisma.blogEvent.findUnique(args);
  }
  async createBlogEvent(
    args: Prisma.BlogEventCreateArgs
  ): Promise<PrismaBlogEvent> {
    return this.prisma.blogEvent.create(args);
  }
  async updateBlogEvent(
    args: Prisma.BlogEventUpdateArgs
  ): Promise<PrismaBlogEvent> {
    return this.prisma.blogEvent.update(args);
  }
  async deleteBlogEvent(
    args: Prisma.BlogEventDeleteArgs
  ): Promise<PrismaBlogEvent> {
    return this.prisma.blogEvent.delete(args);
  }
}
